server:
  port: 7002

eureka:
  instance:
    hostname: localhost # eureka服务端的实例名称
  client:
    # false表示不向注册中心注册自己（eg：物业公司不跟自己收物业费，7002就是物业公司）
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      # 单机版
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # http://localhost(eureka服务端的实例名称):7002/eureka/
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #false关闭自我保护机制，保证不可用服务被及时剔除，默认为true(注册公司未缴纳物业费不给予通融)
    enable-self-preservation: false
    #2毫秒之后剔除
    eviction-interval-timer-in-ms: 2000
    #设置读超时时间
    peer-node-read-timeout-ms: 300