#consul服务端口号
server:
  port: 8004

#注册服务名
spring:
  application:
    name: consul-provider-payment
  #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500  #consul默认端口号为8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
