server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    #将nacos-order-consumer服务注册进8848nacos注册发现中
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider
## 有以上写法则表示在消费者的controller里面不需要定义参数SERVER_URL：
## public static final SERVER_URL = "http://nacos-payment-provider";