server:
  port: 80

eureka:
  client:
    # 表示是否将自己注册进Eureka-Server中，默认为true(是否要入驻并交物业费)
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间(5秒)
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # logging级别feign日志以什么级别监控哪个接口(feign的service接口)
    com.example.springcloud.service.PaymentFeignService: debug