server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  ### 方法一：在配置文件yml中配置gateway网关路由
  cloud:
    gateway:  #代表9527网关挡在8001前面
      routes: #多个路由route的复数，以下有两个路由。访问地址：uri+predicates，要管理几个路由就写几部分。
        - id: payment_routh1 #payment_route  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由，对于@GetMapping中地址

        - id: payment_routh2
          uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**  #断言，路径相匹配的进行路由，对于@GetMapping中地址

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka