server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #GitHub上面的git仓库名字
          uri: https://github.com/HuangYuJue/springcloud-config.git
          #搜索目录
          search-paths:
            - springcloud-config
          #跳过SSL校验，不然报https://github.com/HuangYuJue/springcloud-config.git: cannot open git-upload-pack
          skip-ssl-validation: true
      #读取分支，即分支的名字
      label: master
      #配置读取规则：
      #·{application} 就是应用名称，对应到配置文件上来，就是配置文件的名称部分，例如创建的配置文件config
      #·{profile} 就是配置文件的版本，项目有开发版本、测试环境版本、生产环境版本，对应到配置文件上来就是
      # 以 application-{profile}.yml 加以区分，例如application-dev.yml、application-sit.yml、application-prod.yml
      #·{label} 表示git分支，默认是master分支，如果项目是以分支做区分也是可以的，那就可以通过不同的 label 来控制访问不同的配置文件了


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka