server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #GitHub上面的git仓库名字
          uri: https://github.com/HuangYuJue/springcloud-config.git
          username: HuangYuJue
          password: bevj3vpicj4cvt2
          #搜索目录
          search-paths:
            - springcloud-config
          #跳过SSL校验
          skip-ssl-validation: true
          #并且在git.bash中输入git config --global http.sslVerify false：不然报https://github.com/HuangYuJue/springcloud-config.git: cannot open git-upload-pack
      #读取分支，即分支的名字
      label: master
      #配置读取规则：
      #·{application} 就是应用名称，对应到配置文件上来，就是配置文件的名称部分，例如创建的配置文件config
      #·{profile} 就是配置文件的版本，项目有开发版本、测试环境版本、生产环境版本，对应到配置文件上来就是
      # 以 application-{profile}.yml 加以区分，例如application-dev.yml、application-sit.yml、application-prod.yml
      #·{label} 表示git分支，默认是master分支，如果项目是以分支做区分也是可以的，那就可以通过不同的 label 来控制访问不同的配置文件了

  ##rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672  #15672是rabbitmq的web管理页面的端口，5672才是rabbitmq的默认服务端口(访问的端口)
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"